[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.8.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "v0.6.0"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "v0.2.15"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.2"

[[constraint]]
  name = "github.com/coreos/go-iptables"
  version = "v0.4.0"

[[constraint]]
  name = "github.com/juju/errors"
  branch = "master"

[[constraint]]
  name = "github.com/xaionaro-go/go-ipset"
  branch = "master"
