kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-config
  namespace: kube-ovn
data:
  OVN-NB-SOCKET: ""
  OVN-NB-HOST: "0.0.0.0"
  OVN-NB-PORT: 6641
  KUBECONFIG: ""
  DEFAULT-LS: "ovn-default"
  DEFAULT-CIDR: "10.16.0.0/16"
  DEFAULT-GATEWAY: "10.16.0.1"
  DEFAULT-EXCLUDE-IPS: "10.16.0.0..10.16.0.10"
  CLUSTER-ROUTER: "ovn-cluster"
  NODE-SWITCH: "join"
  NODE-SWITCH-CIDR: "100.64.0.0/16"
  NODE-SWITCH-GATEWAY: "100.64.0.1"
  CLUSTER-TCP-LOADBALANCER: "cluster-tcp-loadbalancer"
  CLUSTER-UDP-LOADBALANCER: "cluster-udp-loadbalancer"
  BIND-SOCKET: "/var/run/cniserver.sock"
  OVS-SOCKET: ""
